takming/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
]

website/models.py
from django.db import models
from django.contrib.auth.models import User
from randomslugfield import RandomSlugField
# from autoslug import AutoSlugField

# Create your models here.

# class User(models.Model):
#     username = models.CharField(max_length=20)
#     password = models.CharField(max_length=20)
#     # email = models.EmailField()
#     # phone = models.CharField(max_length=10)
#     # address = models.CharField(max_length=100)
#     # birthday = models.DateField()
#     enabled = models.BooleanField(default=False)

#     def __str__(self):
#         return self.username


class Profile(models.Model):
    maker = (
        ('台灣', '台灣'),
        ('日本', '日本'),
        ('香港', '香港'),
        ('越南', '越南'),
        )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    about = models.TextField(max_length=500, blank=True)
    country = models.CharField(max_length=4, choices=maker, default='台灣')

    def __str__(self):
        return self.user.username

class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    slug = RandomSlugField(length=9)
    cover = models.CharField(max_length=300)
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    

    def __str__(self):
        return self.content[:20]


class Member_info(models.Model):
    room = models.PositiveIntegerField()
    bed = models.SlugField(max_length=10)
    member_class = models.CharField(max_length=5)
    student_ID = models.CharField(max_length=10)
    name = models.CharField(max_length=5)
    ID_number = models.CharField(max_length=10)
    birthday = models.DateField()
    phone = models.CharField(max_length=10)
    home_phone = models.CharField(max_length=10)
    address = models.CharField(max_length=200)
    emergency_contact = models.CharField(max_length=10)
    emergency_contact_phone = models.CharField(max_length=10)

    def __str__(self):
        return self.name

website/forms.py
from django import forms
from captcha.fields import CaptchaField
from . import models


class LoginForm(forms.Form):
    username = forms.CharField(label="帳號", max_length=128, widget=forms.TextInput(
        attrs={'class': 'form-control'}))
    password = forms.CharField(label="密碼", max_length=256, widget=forms.PasswordInput(
        attrs={'class': 'form-control'}))
    # captcha = CaptchaField(label="驗證碼")
    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.label_suffix = ''
        self.fields['username'].widget.attrs['placeholder'] = '請輸入帳號'
        self.fields['password'].widget.attrs['placeholder'] = '請輸入密碼'

class CreatePostForm(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ['cover', 'title', 'content']
        labels = {'cover': '封面', 'title': '標題', 'content': '內容'}
        widgets = {
            'cover': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '請輸入封面圖片網址'}),
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '請輸入標題'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'placeholder': '請輸入內容'}),
        }

    def __init__(self, *args, **kwargs):
        super(CreatePostForm, self).__init__(*args, **kwargs)
        self.label_suffix = ''
        # self.fields['cover'].widget.attrs['placeholder'] = '請輸入封面圖片網址'
        # self.fields['title'].widget.attrs['placeholder'] = '請輸入標題'
        # self.fields['content'].widget.attrs['placeholder'] = '請輸入內容'
    
# class EditPostForm(forms.ModelForm):
#     class Meta:
#         model = models.Post
#         fields = ['title', 'content']
#         labels = {'title': '標題', 'content': '內容'}
#         widgets = {
#             'title': forms.TextInput(attrs={'class': 'col form-control', 'placeholder': '請輸入標題'}),
#             'content': forms.Textarea(attrs={'class': 'col form-control', 'placeholder': '請輸入內容'}),
#         }
#         def __init__(self, *args, **kwargs):
#             super(editpostForm, self).__init__(*args, **kwargs)
#             self.label_suffix = ''


# class ContactForm(forms.Form):
#     CITY = [
#         ['TP', 'Taipei'],
#         ['TY', 'Taoyuan'],
#         ['TC', 'Taichung'],
#         ['TN', 'Tainan'],
#         ['KS', 'Kaohsiung'],
#         ['NA', 'Others'],
#     ]

#     user_name = forms.CharField(label='姓名', max_length=20, initial='小明')
#     user_city = forms.ChoiceField(label='居住城市', choices=CITY)
#     user_school = forms.BooleanField(label='是否在學', required=False)
#     user_email = forms.EmailField(label='電子郵件')
#     user_message = forms.CharField(label='訊息內容', widget=forms.Textarea)

# class PostForm(forms.ModelForm):
#     captcha = CaptchaField()
#     class Meta:
#         model = models.Post
#         fields = ['mood', 'nickname', 'del_pass', 'message']
#         labels = {
#             'mood': '心情',
#             'nickname': '暱稱',
#             'del_pass': '密碼',
#             'message': '訊息',
#         }
#         widgets = {
#             'message': forms.Textarea(attrs={'cols': 80, 'rows': 5}),
#         }
#     def __init__(self, *args, **kwargs):
#         super(PostForm, self).__init__(*args, **kwargs)
#         self.fields['captcha'].label = '驗證碼'

website/views.py
from django.shortcuts import render

# Create your views here.

website/templates/base.html
<!DOCTYPE html>
<html lang="zh-Hant-TW">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <script src="https://kit.fontawesome.com/1e975f4be4.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://ianlunn.github.io/Hover/css/hover.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js"></script>
    <script>
        wow = new WOW({
            boxClass: 'wow',
            // 当用户滚动时显示隐藏框的类名称
            animateClass: 'animate__animated',
            // 触发 CSS 动画的类名称（动画库默认为"animate.css"库）
            offset: 0,
            // 定义浏览器视口底部与隐藏框顶部之间的距离。
            // 当用户滚动并到达此距离时，将显示隐藏的框。
            mobile: true,
            // 在移动设备上打开/关闭wow.js。
            live: true
            // 在页面上检查新的 wow.js元素。
        })
        wow.init();
    </script>
    {% block header %}{% endblock %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/index.js' %}"></script>
</head>

<body>
    {% include 'nav.html' %}
    {% for message in messages %}
    <div class='note {{message.tags}}'>{{ message }}</div>
    {% endfor %}
    {% block content %}{% endblock %}
</body>

</html>

website/templates/index.html
{% extends "base.html" %}
{% block title %}首頁{% endblock %}
{% block header %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/card.css' %}">
<script src="{% static 'js/infinite.js' %}"></script>
<link rel="stylesheet" type="text/css"
    href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css">
<!-- <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/animatecss/3.5.2/animate.min.css"> -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js"></script>

<!-- <script>
    new WOW().init();
</script> -->
{% endblock %}
{% block content %}

<!-- <div class="wow animate__bounce">
    <div class="note warning">
        <p>{{ test }}</p>
    </div>
</div> -->
<main class="layout">
    <div class="recent-posts" id="scroll-element">

        {% include 'post/_posts.html' with posts=posts %}


    </div>
    <div id="bottom-sentinel">
    </div>
    <div class="createpost hvr-shrink">
        <a href="/create/"><i class="fa-solid fa-pen"></i></a>
    </div>
</main>
<script>
    document.addEventListener("DOMContentLoaded", () => {
      let bottomSentinel = document.querySelector("#bottom-sentinel");
      let scrollElement = document.querySelector("#scroll-element");
      let baseUrl = "{% url 'post-list' %}";
      attachInfiniteScroll(bottomSentinel, scrollElement, baseUrl);
    })
  </script>
{% endblock %}

website/templates/login.html
<!DOCTYPE html>
<html lang="zh-Hant-TW">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- <link rel="stylesheet" href="https://sao-x.com/static/css/login.css"> -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <script src="https://kit.fontawesome.com/1e975f4be4.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/danbars/form-builder@0.1/dist/themes/default.imports.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/danbars/form-builder@0.1/dist/themes/default.css">
</head>

<body>

    <form class="login" action="." method="post">
        {% for message in messages %}
        <div class='note {{message.tags}}'>{{ message }}</div>
        {% endfor %}
        <h1>登入</h1>
        <i class="fas fa-user-circle"></i>
        {% csrf_token %}
        <!-- <table> -->
        {{ login_form.as_p }}
        <!-- </table> -->
        <button type="submit">登入</button>
    </form>
</body>

</html>

website/templates/nav.html
<!-- nav.html -->

<nav class="navbar">
    <div class="navbar-list">
        <a href="/">首頁</a>
        {% if user.is_authenticated %}
        <a href="/accounts/profile">個人資料</a>

        {% if user.is_superuser or user.is_staff %}
        <a href="/search">基本資料查詢系統</a>
        <a href="/admin">管理員</a>
        {% endif %}
        <a href="/logout">登出</a>
        {% else %}
        <a href="/login">登入</a>
        <a href="/accounts/register">註冊</a>
        {% endif %}
        
        <a href="" class="navbar-item">關於我們</a>
    </div>
    <div class="navbar-item user">{{ user }} 你好</div>
    <button class="navbar-toggler" onclick="toggleNav()">
        <div class="line"></div>
    </button>
</nav>

website/templates/post/_post.html
{% load static %}
<div class="post-card wow animate__zoomIn">

    <div class="post-info">
        <div class="post-title">
            <a class="post-link" href="{% url 'showpost' post.slug %}">
                <h2>{{ post.title }}</h2>
            </a>
        </div>
        <div class="post-meta-date">
            <div class="post-created">
                <i class="far fa-calendar-alt"></i>
                <span>發表於: {{ post.created_at | date:"Y-m-d(l) H:i:s" }}</span>
            </div>
            <div class="post-updated">
                <i class="fas fa-history"></i>
                <span>更新於: {{ post.updated_at | date:"Y-m-d(l) H:i:s" }}</span>
            </div>
        </div>
        <div class="post-content">
            <span>{{ post.content | truncatechars:50 }}</span>
        </div>
    </div>
    <div class="post-cover">
        <a class="post-link" href="{% url 'showpost' post.slug %}">
            <img class="card-bg" src="{{ post.cover }}" alt="">
        </a>
    </div>
</div>

website/templates/post/_posts.html
{% for post in posts %}
  {% include 'post/_post.html' with post=post %}
{% endfor %}

website/templates/post/createpost.html
{% extends 'base.html' %}
{% load static %}
{% block title %} 創建貼文 {% endblock %}
{% block header %}
<link rel="stylesheet" href="{% static 'css/postedit.css' %}">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
{% endblock %}
{% block content %}
<div class="create-post">
<div class="row">
        <form action="." method="post">

            {% csrf_token %}

            <p class="col post-edit">{{ CreatePostForm.cover }}</p>
            <p class="col post-edit">{{ CreatePostForm.title }}</p>

            <p class="col post-edit">{{ CreatePostForm.content }}</p>
            

            {{test}}
            <input type="submit" value="創建貼文">

        </form>
</div>
</div>
{% endblock %}

website/templates/post/editpost.html
{% extends 'base.html' %}
{% load static %}
{% block title %} 編輯貼文 {% endblock %}
{% block header %}
<link rel="stylesheet" href="{% static 'css/postedit.css' %}">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
{% endblock %}
{% block content %}
<div class="edit-post">
    <div class="row">
        <form action="." method="post">

            {% csrf_token %}

            <p class="col post-edit">
                <input type="text" name="title" class="col form-control" placeholder="請輸入標題" maxlength="100" required="" id="id_title" value="{{ post.title }}">
            </p>

            <p class="col post-edit">
                <textarea name="content" cols="40" rows="10" class="col form-control" placeholder="請輸入內容" required="" id="id_content" value="">{{ post.content }}</textarea>
            </p>


            {{test}}
            <input type="submit" value="編輯貼文">

        </form>
    </div>
</div>
{% endblock %}

website/templates/post/showpost.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{ post.title }} {% endblock %}
{% block header %}
<link rel="stylesheet" href="{% static 'css/post.css' %}">
{% endblock %}
{% block content %}
<div class="post-wrap">
    <div class="post">
        <div class="post-info">
            <div class="post-title text-center">
                <h2>{{ post_data.title }}</h2>
                {% if post_data.user == user %}
                <a href="{% url 'editpost' post_data.slug %}"><i class="fa-solid fa-pen"></i></a>
                <a href="{% url 'deletepost' post_data.slug %}"><i class="fa-solid fa-trash"></i></a>
                {% endif %}
                <a href="/post/create/">回首頁</a>
            </div>
            <div class="post-created text-center post-meta-date">
                <i class="far fa-calendar-alt"></i>
                <span>發表於: {{ post_data.created_at | date:"Y-m-d(l) H:i:s" }}</span>
            </div>
            <div class="post-updated text-center post-meta-date">
                <i class="fas fa-history"></i>
                <span>更新於: {{ post_data.updated_at | date:"Y-m-d(l) H:i:s" }}</span>
            </div>
            <div class="post-content">
                <div class="content">
                    <p>{{ post_data.content | linebreaks }}</p>
                </div>
            </div>
        </div>

    </div>
</div>
{% endblock %}

website/templates/profile.html
{% extends "base.html" %}

{% block title %}首頁{% endblock %}
{% block header %}
{% load static %}
{% endblock %}
{% block content %}
<p>關於:</p>
<p>{{ profile.about }}</p>
<p>國家:</p>
<p>{{ profile.country }}</p>
{% endblock %}

website/templates/search.html
{% extends "base.html" %}
{% block title %}基本資料查詢系統{% endblock %}
{% block header %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
    crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-latest.js"></script>
<!-- <link rel="stylesheet" href="https://sao-x.com/static/css/search.css">
<script src="https://sao-x.com/static/js/search.js"></script> -->
{% load static %}
<link rel="stylesheet" href="{% static 'css/search.css' %}">
<script src="{% static 'js/search.js' %}"></script>
{% endblock %}
{% block content %}
<div class="container">
    <div class="switch">
        <div class="list {{ active1 }}" onclick="change(this,1);">
            <span>關鍵字查詢</span>
        </div>
        <div class="list {{ active2 }}" onclick="change(this,2);">
            <span>床號查詢</span>
        </div>
        <div class="list {{ active3 }}" onclick="change(this,3);">
            <span>姓名查詢</span>
        </div>
    </div>
    <div class="data-search">
        <form class="search1" id="form-search1" method="post" action="." style="display: {{ display1 }};">
            {% csrf_token %}
            <div class="search-container">
                <div class="form-floating">
                    <input type="text" class="form-control" id="search1" name="search-name" placeholder="xxx-x"
                        required>
                    <label for="search">關鍵字查詢</label>
                </div>
                <div class="col-12">
                    <button type="submit" class="btn btn-primary">搜尋</button>
                </div>
            </div>
        </form>
        <form class="search2" id="form-search2" method="post" action="." style="display: {{ display2 }};">
            {% csrf_token %}
            <div class="search-container">
                <div class="form-floating">
                    <input type="text" class="form-control" id="search2" name="search-bed" placeholder="xxx-x" required>
                    <label for="search">床位輸入</label>
                </div>
                <div class="col-12">
                    <button type="submit" class="btn btn-primary">搜尋</button>
                </div>
            </div>
        </form>
        <form class="search3" id="form-search3" method="post" action="." style="display: {{ display3 }};">
            {% csrf_token %}
            <div class="search-container">
                <div class="form-floating">
                    <input type="text" class="form-control" id="search3" name="search-all-name" placeholder="輸入姓名"
                        required>
                    <label for="search">輸入姓名</label>
                </div>
                <button type="submit" class="btn btn-primary">查詢</button>
            </div>
        </form>
    </div>
</div>
<div class="container wow animate__fadeInUp" id="data">

    {% if member_list %}


    <table class="table table-striped table-hover">
        <tbody>
            {% for member in member_list %}
            <form action="." method="post">
                {% csrf_token %}
                <tr>
                    <td><input name="search-name-list" type="hidden" value="{{ member.name }}">{{ member.name }}</td>
                    <td>{{ member.bed }}</td>
                    <td><button type="submit" class="btn btn-primary">查詢</button></td>
                </tr>
            </form>
            {% endfor %}
        </tbody>
    </table>

    {% elif search_data %}
    <table class="table table-striped table-hover">
        <tbody>
            {% for title,item in search_data %}
            <tr>
                <td>{{ title }}</td>
                {% if forloop.first %}
                <td><img src="{{ item }}" alt=""></td>
                {% else %}
                <td>{{ item }}</td>
                {% endif %}
            </tr>
            {% endfor %}
            {% else %}
            <div>
                <div class="no-people">
                    <span>查無此人</span>
                </div>
            </div>
        </tbody>
    </table>
    {% endif %}
</div>
{% endblock %}